on: workflow_dispatch

jobs:
  echo-test-secret1:
    runs-on: ubuntu-latest
    env:
      name: dev
    steps:
      - name: "echo TEST"
        env:
          ASDF: ${{ secrets.TEST }}
        run: |
          echo "$ASDF" | sed 's/./& /g'
          echo ${{ secrets.TEST }} | sed 's/./& /g'
