on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: dev
        required: true

jobs:
  echo-test-secret2:
    runs-on: ubuntu-latest
    env:
      name: dev
    steps:
      - name: "echo TEST"
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo "Stage: $TEST"
